import unittest
import moc_submit_lastfm as MOC

class TestExtractInfo(unittest.TestCase):
	def check_info(self, artist, album, title, info):
		if isinstance(info, str):
			info = MOC.extract_tags_from_filename(info)
		self.assertEqual(info.artist, artist)
		self.assertEqual(info.album, album)
		self.assertEqual(info.title, title)

	def test_should_substitute_insufficient_info(self):
		info = MOC.TrackInfo(artist="artist")
		extended = MOC.TrackInfo(artist="extended_artist", title="extended_title")
		info = MOC.substitute_insufficient_info(info, extended)
		self.check_info("artist", None, "extended_title", info)
	def test_should_extract_tags_from_filename(self):
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000-Album/01-Title.mp3")
		self.check_info("Artist", None, "Title", "/media/music/Artist - Title.mp3")
		self.check_info("Artist", None, "Title", "/media/music/12-Artist/01-Title.mp3")
		self.check_info(None, "Album", "Title", "/media/music/2000 - Album/01-Title.mp3")
		self.check_info(None, "Album Name", "Title Name", "/media/music/2014.Album Name/01 Title Name.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/Album/01 Title Name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Album-2009/01 - Title.mp3")
		self.check_info("Artist", "Album Name", "Title Name", "/media/music/Artist-Album_Name-2000-r35/01-Artist-Title_Name.mp3")
		self.check_info("Artist", "Album Name", "Title Name", "/media/music/Artist Name - Album Name (2000)/01 - Title Name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album/01 - Title.mp3")
		self.check_info("Artist", "Album Name", "Title", "/media/music/Artist/[2000] Album Name/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Artist - Album (2000)/Artist - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (Limited Edition) (2000)/01-Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album [320kb]/Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album (Live) [320kb]/Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Artist - Album [2000]/01 Title.MP3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01 Title.wma")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01) Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums/(2000) Artist - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album/01. Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Re-release 2000)/01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Deluxe Edition 2000)/01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Remastered 2000)/01-artist_name-title.mp3")
		self.check_info("Artist Name", "Album", "Title Name", "/media/music/Artist_Name_Discography/2000 - Album (Remastered 2000/01-artist_name-title_name.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Reissue 2000)/Artist Name - 01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Japanese Version)/01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Expanded Edition)/01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title", "/media/music/Artist_Name_Discography/2000 - Album (Limited Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography Vbr Mp3/2000 Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography Vbr Mp3/2000 Album/01-Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist Discography Vbr Mp3/2000 Album/01-Title_Name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography [ALL ALBUMS][MP3@320Kbps CBR] ~12A34B~/[2000] Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography [ALL ALBUMS][MP3@320Kbps CBR] ~12A34B~/[2000]-[2000] Album (Special Edition)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography [ALL ALBUMS][MP3@320Kbps CBR] ~12A34B~/[2000] Album (Special Edition)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album (2000 г., some, ABCD 123456)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album  (2000 г., some, CD-CRCD 1234-56, CDL-123-45)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album (2000 г., some, CD-CRCD 1234-56, CDL-123-45)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album (2000 г., some, CD-CRCD 1234-56, CDL-123-45)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album (2000 г., some, 1234 567-8)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album (2000 г., some, AB-C+123-4)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Albums, Live, Compilations/2000 - Artist - Album (2000 г., some, AB 1234567)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist and side-projects/Artist/2000 - Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album/00 Title (Intro).mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album/01  Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/01. Studio Album's/(2000)Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/01. Studio Album's/(2000)Album (Japanese Edition)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/01. Studio Album's/(2000) Album (Deluxe Edition)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/02. Demo Albums/(2000)Album (Limited Edition)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/04. Extended Play's/(2000) Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Апьбомы, сингл, сборник/2000 - Album (Ремастер 2008)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Апьбомы, сингл, сборник/2000 - Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Апьбомы, сингл, сборник/2000 - Album (French Remaster)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Апьбомы, сингл, сборник/2000 - Album/CD1/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Апьбомы, сингл, сборник/2000 - Album/CD2/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Апьбомы, сингл, сборник/2000 - Album (Коллекционное издание)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album [#12345 67890 1]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album (Limited Edition) [#12345 67890 1]/33. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album (Limited Edition) [#12345 67890 1]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album (Advanced Album) (Promo Edition)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album [#12345 678901]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album (Limited Edition) [#12345-6]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album (Limited Edition) [#123456-7]/CD1/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000 - Album (Limited Edition) [# 1234 56789 0]/CD 1 (Disk Name)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist-Discography.2000-2000.MP3/01 - Albums/2000- Album (Limited Edition Collector's Pack) [#ABCDE012F]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/Album/01 Title_name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01.ARTIST - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01 - ARTIST - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01.Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Artist - Album/02. Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01-artist-Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01 - ARTIST - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Album/01. Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/Album/12+-+ARTIST+-+Title+name.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/Album/09 - Title Name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/ARTIST/2000 - Album/01. Title - Artist.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/ARTIST/2000 - Album (Single)/01. Title - Artist.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/ARTIST/2000 - Album 2CD/CD #1 (Live At Stadium)/01. Title - Artist.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/01.Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/ARTIST DiscograPHY/2000-Album/1 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/ARTIST DiscograPHY/2000-Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/ARTIST DiscograPHY/2000-Artist - Album/01-artist-title_name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - 12 Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000) [mp3@320]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist -2000- Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/(2000)  Album (EP)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/(2000) Album/01_-_Title_name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/(2000)  Album (EP)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/(2000)Album (Single)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album (Переиздание)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album [WEB]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title Name", "/media/music/Artist Name/Album/01-artist_name-title_name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/EPs and Singles/2000 - Album (EP)/1 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/EPs and Singles/2000 - Album/1 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/EPs and Singles/2009 - Album EP/Artist - Album 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/Other albums/2000 - Artist - Album/1 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/Other albums/2000 - Artist - Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/Other albums/2000 - Artist - Album/Artist - Album - 09 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/Other albums/2000 - Artist - Album (Japanese Import)/CD 1/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/Other albums/2000 - Artist - Album (Japanese Import)/CD 2/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography @ 320 (1 Albums + 1 Singles)(Genre)(by someone)/Studio/2000 - Artist - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album/1. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album (Remaster 2000)/01. 12 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01. 12 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (Special Edition) [Digitally Re-Mastered 2000]/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (US Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (US Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album [US Edition EP]/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (Live At Place 2000)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (US Limited Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (US Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album [US Edition EP]/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (US Limited Edition)/18 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (Live)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (US Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album (Japanese Edition)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - DISCOGRAPHY (2000-00) [SOME TAGS]/[2000] Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01-Album-Title-Artist.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/Artist - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01-Artist - title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (Japan Limited Edition) 2000/01. Title_[example.com].mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 Album/CD 1/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 Album/CD 2/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 Album (EP)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist [Discography]/2000-Album (320)/01-Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography/2000 - 320kbps - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist [320] by SomeOne/Artist [2000] Album [320] by SomeOne/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album/1.Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (Deluxe Edition) MP3   320k ab1234/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01. ...Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/1. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/01-Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/1 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Discography (2000 - 2000)/2000 - Album/01 - Title.mp3")
		self.check_info("Artist Name", "Album", "Title Name", "/media/music/Artist Name - Album (2012) [mp3@VBR]/01-artist_name-title_name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2009)/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (Demo)/Artist - Album - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (Demo)/Artist - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (Single)/Artist - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (EP)/Artist - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album/CD 1/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album/CD 2/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (Single)/01 - ARTIST - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (Live)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/[2000] Album (Compilation)/01_title_name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album (Single)/Artist - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/[2000] Album (Live)/01-title_name-vic.mp3")
		self.check_info("Artist", "Album", "Title Name", "/media/music/Artist/[2000] Album (Live)/01- Title Name.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album/ARTIST - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album Reissue/Album Bonus Disc/Artist - Album [Reissue Bonus Disc] - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/[2000] Album Reissue/Album/Artist - Album [Reissue] - 01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/1. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album (переиздание)/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album (сингл)/6.Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album (сингл)/1 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/01. Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist Discography/(2000) Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist. Дискография. Часть 1. Официальная/Artist/2000 Album/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist. Дискография. Часть 1. Официальная/Artist/2000 Album/CD1/01 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist. Дискография. Часть 1. Официальная/Artist/2000 Album/CD2/1 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist. Дискография. Часть 1. Официальная/Other Artist/2000 Album/03 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist. Дискография. Часть 1. Официальная/Other Artist/2000 Album/04 Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Дискография/Альбомы/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Дискография/Концертные альбомы/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Дискография/Сборники/2000 - Album (сборник)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Дискография/Синглы/2000 - Album (сингл)/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Sounds/+ Live/2000 - Album/01 - Artist title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Sounds/+ Live/2000 - Album/01 -  Title.mp3")
		self.check_info("Artist", "Album", "Artist 12", "/media/music/Artist/Sounds/2000 - Album/01 - Artist 12.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Sounds/2000 - Album 00/01 - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Sounds/2000 - Album (15-трековое издание)/01 - Title.mp3")
		self.check_info("Artist", "7", "Artist 07", "/media/music/Artist/Sounds/2000 - 7/01 - Artist 07.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Sounds/2000 - Album/03. Other Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Sounds/2000 - Album/04. Artist - Title.mp3")
		self.check_info("Artist", None, "Title", "/media/music/Artist/Sounds/Bonus/Artist - Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist/Studio/2000 - Album/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Концерты/2000 - Album (Label, AB 123-456, 2000) 2CD [flac]/CD1/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Концерты/2000 - Album (Label., ABC 123456 7, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Концерты/2000 - Album (Label, AB 123-4, 2000) 2CD [flac]/CD1/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Концерты/2000 - Album (Label, AB 123-4, 2000) 2CD [flac]/CD2/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Singer Name/2000 - Album (подарочное издание) (Label, AB 123-4, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Сборники/2000 - Album (Label, ABC 123, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Сборники/2000 - Album (подарочное издание) (Label, AB-123-CD, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Сборники/2000 - Album (Label, ABC 123, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Сборники/2000 - Album (Label, AB CD-123, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Сборники/2000 - Album (Label, AB 123-4, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Синглы/2000 - Album (Label., ABC 123456 7, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Синглы/2000 - Album (Label., ABC 123456 7, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/+ Синглы/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/13. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/10. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB-123-4, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB-123 CD, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - 12-a Album (Limited Edition) (Label, ABC 123456 7, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/01. Title.).mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CDp, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234 CD, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist (Singer Name)/2000 - Album (Label, AB 1234CDp, 2000) [flac]/01. Title.mp3")
		self.check_info("Artist", "Album", "Title", "/media/music/Artist - Album (2000)/Artist - Full Album (2000)/01. Title.mp3")

class TestDecoding(unittest.TestCase):
	def test_should_leave_ascii_as_is(self):
		info = MOC.TrackInfo(artist="artist", title="title", album="album")
		info = MOC.decode_info(info)
		self.assertEqual(info.artist, "artist")
		self.assertEqual(info.album, "album")
		self.assertEqual(info.title, "title")
	def test_should_recognize_utf_8(self):
		info = MOC.TrackInfo(artist="ÐÐ¸ÐºÐ½Ð¸Ðº", title="ÐÐ¾ÑÑ", album="ÐÑÐ¼")
		info = MOC.decode_info(info)
		self.assertEqual(info.artist, "Пикник")
		self.assertEqual(info.album, "Дым")
		self.assertEqual(info.title, "Ночь")
	def test_should_recognize_cp1251(self):
		info = MOC.TrackInfo(artist="Ñïëèí", title="Óâåðòþðà", album="Îáìàí çðåíèÿ")
		info = MOC.decode_info(info)
		self.assertEqual(info.artist, "Сплин")
		self.assertEqual(info.album, "Обман зрения")
		self.assertEqual(info.title, "Увертюра")
	def test_should_recognize_iso8859_1(self):
		info = MOC.TrackInfo(artist="The Gathering", title="Eléanor", album="Mandylion")
		info = MOC.decode_info(info)
		self.assertEqual(info.artist, "The Gathering")
		self.assertEqual(info.album, "Mandylion")
		self.assertEqual(info.title, "Eléanor")

class TestInfo(unittest.TestCase):
	def test_should_create_info_object_from_other_object(self):
		info = MOC.TrackInfo(title="some_title")
		cloned_info = MOC.TrackInfo(info)
		self.assertEqual(cloned_info.title, "some_title")
		cloned_info.title = ""
		self.assertEqual(info.title, "some_title")
	def test_should_recognize_full_specified_length(self):
		self.assertEqual(MOC.convert_length("10:10"), 10 * 60 + 10)
	def test_should_recognize_only_minutes_length(self):
		self.assertEqual(MOC.convert_length("10"), 10)

if __name__ == '__main__':
	unittest.main()
